### ISSUE TITLE
Add a `leftover` attribute for anything left over after decompression

### ISSUE THREAD

**Issue by bluesmoon** [nicjansma/resourcetiming-compression.js#11]
Since the compression algorithm is extensible, it is possible for extensions to append new data by adding a new `SPECIAL_DATA_XXX_TYPE`. This additional data is lost when decompressing because the decompressor only includes special types that it knows about (size and dimension).

It would be good if the decompressor added whatever was left over that it couldn't handle so that the caller can take care of parsing that section.

**Comment by nicjansma** [comment]
This is now addressed via https://github.com/nicjansma/resourcetiming-compression.js/pull/24
