### ISSUE TITLE
Ability to skip Resource Dimensions data gathering 

### ISSUE THREAD

**Issue by bfrost2893** [nicjansma/resourcetiming-compression.js#27]
Hi Nic,

I would like the ability to skip gathering Resource Dimensions. I already have the access to this information, and we would like to prevent any potential style/layout recalculations that might occur from invoking element size methods. It could be as simple as a flag that is passed to `compressResourceTiming`.

Let me know what you think.

Brad

**Comment by nicjansma** [comment]
Great idea!  Published in v1.2.4: https://github.com/nicjansma/resourcetiming-compression.js/commit/6af733b321f0135a2fdd2f018ba27f578e0b3436
