### ISSUE TITLE
Malformed decompression

### ISSUE THREAD

**Issue by aftabnaveed** [nicjansma/resourcetiming-compression.js#28]
When trying to decompress the resources I get a malformed name.

Resource Name:
``http://localhost:3000/plugins/guid.min.js```

```javasript
app.post('/beacon', (req, resp) => {
  let rt = req.body.restiming;
  if (rt !== undefined) {
        console.log(ResourceTimingDecompression.decompressResources(JSON.parse(rt)));
  }
});
```

Here is the output:
Note* the host is in the reverse order.
```
 { name: 'http://0003:tsohlacol/plugins/guid.min.js',
    initiatorType: 'script',
    startTime: 103,
    redirectStart: 0,
    redirectEnd: 0,
    fetchStart: 103,
    domainLookupStart: 127,
    domainLookupEnd: 127,
    connectStart: 127,
    secureConnectionStart: 0,
    connectEnd: 127,
    requestStart: 128,
    responseStart: 131,
    responseEnd: 134,
    duration: 31,
    encodedBodySize: 850,
    transferSize: 1156,
    decodedBodySize: 850,
    scriptAsync: false,
    scriptDefer: false,
    scriptBody: true }
```

What can I do to fix it?

**Comment by nicjansma** [comment]
Hi @aftabnaveed!

You can set the `ResourceTimingDecompression.HOSTNAMES_REVERSED` flag to control if hostnames are reversed or not (which can lead to better compression).

https://github.com/nicjansma/resourcetiming-compression.js/blob/master/src/resourcetiming-decompression.js#L31
